import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import {
  SignedOut,
  useUser,
  SignInButton,
  SignedIn,
  UserButton,
} from "@clerk/nextjs";
import { Fragment } from "react";

const Home: NextPage = () => {
  const { data } = api.question.getAll.useQuery();

  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <SignedIn>
          <UserButton />
          {user?.user?.fullName}
          <div>
            {data?.map((question) => (
              <Fragment key={question.id}>
                <div>{`${question.id}. ${question.content}`}</div>
                {Array.isArray(question.options) &&
                  question.options.map((option) => <div>{option}</div>)}
              </Fragment>
            ))}
          </div>
        </SignedIn>
        <SignedOut>
          <SignInButton />
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
