import { type GetServerSideProps, type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import {
  SignedOut,
  useUser,
  SignInButton,
  SignedIn,
  UserButton,
} from "@clerk/nextjs";
import { generateSSRHelper } from "~/server/helpers/ssrHelper";
import Link from "next/link";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const ssr = generateSSRHelper(context);

  await ssr.exam.getExams.prefetch();

  return {
    props: {
      trpcState: ssr.dehydrate(),
    },
  };
};

const Home: NextPage<{ examId: number }> = ({ examId }) => {
  const { data: exams } = api.exam.getExams.useQuery();

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <SignedIn>
          <UserButton />
          Hello {user?.user?.fullName}
          {exams?.map((exam) => (
            <Link href={`/exam/${exam.id}`}>{exam.timestamp.toString()}</Link>
          ))}
        </SignedIn>
        <SignedOut>
          <SignInButton />
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
